begin;
do $$
declare a uuid:=gen_random_uuid(); v uuid:=gen_random_uuid(); s uuid:=gen_random_uuid(); vs uuid:=gen_random_uuid();
  revision bigint; result jsonb; target text; caught boolean;
begin
  insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values(a,a::text||'@example.invalid',now(),'{}'),(v,v::text||'@example.invalid',now(),'{}');
  insert into auth.sessions(id,user_id) values(s,a),(vs,v);
  insert into private.team_members(auth_id,username,full_name,role) values(a,'accounttestadmin','Test Admin','admin');
  insert into private.team_members(auth_id,username,full_name,role,employee_id) values(v,'accounttestvisitor','Test Visitor','visitor','testemployee');
  update private.team_workspace set state=jsonb_set(state,'{employees}','[{"id":"testemployee","fullName":"Prueba"}]') where id=1;
  select w.revision into revision from private.team_workspace w where id=1;
  result:=public.team_account_change(a,s,revision,'save',jsonb_build_object('fullName','Invitado Test','username','invitetest','email','invite-test@example.invalid','role','visitor','employeeId','testemployee'),null);
  revision:=revision+1;
  if result->>'email'<>'invite-test@example.invalid' then raise exception 'TEST_INVITE_EMAIL'; end if;
  select 'invite:'||id::text into target from private.team_invites where username='invitetest';
  perform public.team_account_change(a,s,revision,'save',jsonb_build_object('fullName','Nombre Editado','username','invitetest2','email','invite-test@example.invalid','role','visitor','employeeId','testemployee'),target);
  revision:=revision+1;
  if (select full_name from private.team_invites where username='invitetest2')<>'Nombre Editado' then raise exception 'TEST_INVITE_EDIT'; end if;
  result:=public.team_accounts_list(a,s);
  if not exists(select 1 from jsonb_array_elements(result) r where r->>'email'='invite-test@example.invalid') then raise exception 'TEST_LIST'; end if;
  caught:=false;
  begin perform public.team_accounts_list(v,vs); exception when others then if sqlerrm='TEAM_ACCESS_DENIED' then caught:=true;else raise;end if;end;
  if not caught then raise exception 'TEST_VISITOR_READ'; end if;
  caught:=false;
  begin perform public.team_account_change(v,vs,revision,'delete','{}',target); exception when others then if sqlerrm='TEAM_ACCESS_DENIED' then caught:=true;else raise;end if;end;
  if not caught then raise exception 'TEST_VISITOR_CHANGE'; end if;
  caught:=false;
  begin perform public.team_account_change(a,s,revision,'toggle','{}',a::text); exception when others then if sqlerrm='TEAM_SELF_PROTECTED' then caught:=true;else raise;end if;end;
  if not caught then raise exception 'TEST_SELF'; end if;
  caught:=false;
  begin perform public.team_account_change(a,s,revision-1,'delete','{}',target); exception when others then if sqlerrm='TEAM_REVISION_CONFLICT' then caught:=true;else raise;end if;end;
  if not caught then raise exception 'TEST_REVISION'; end if;
  perform public.team_account_change(a,s,revision,'save',jsonb_build_object('fullName','Visitor Editado','username','editedvisitor','email',v::text||'@example.invalid','role','visitor','employeeId','testemployee'),v::text);
  revision:=revision+1;
  if (select username from private.team_members where auth_id=v)<>'editedvisitor' then raise exception 'TEST_MEMBER_EDIT'; end if;
  if public.team_login_target('EDITEDVISITOR',repeat('a',64))<>v::text||'@example.invalid' then raise exception 'TEST_ALIAS'; end if;
  perform public.team_account_change(a,s,revision,'toggle','{}',v::text); revision:=revision+1;
  if public.team_login_target('editedvisitor',repeat('a',64))<>'unknown-account@invalid.example' then raise exception 'TEST_DISABLED_LOGIN'; end if;
  perform public.team_account_change(a,s,revision,'delete','{}',target); revision:=revision+1;
  if exists(select 1 from private.team_invites where username='invitetest2') then raise exception 'TEST_CANCEL_INVITE'; end if;
  for counter in 1..10 loop perform public.team_login_target('limit-test',repeat('b',64));end loop;
  if public.team_login_target('limit-test',repeat('b',64)) is not null then raise exception 'TEST_LOGIN_LIMIT'; end if;
end $$;
rollback;
